### ISSUE TITLE
Viewconfig JSON editor

### ISSUE THREAD

**Issue by nvictus** [higlass/higlass-app#7]
All the flexibility in your hands, without the clunky export, edit, save, and reload.

My most common use case -- and pain point -- is adding additional `trackSourceServer`s.

**Comment by flekschas** [comment]
I thought about that too. It would awesome to have something like it but I think it's non trivial to make sure that all the possibilities are supported and that it doesn't get too confusing. I quickly sketched up an idea but that is already non trivial 😅

![screen shot 2018-11-21 at 3 29 51 pm](https://user-images.githubusercontent.com/932103/48866866-50bf4f80-eda2-11e8-929c-303b08227fcb.png)

Adding new track source server should be relatively easy. I think we just didn't get around it yet. Let me add a ticket to the main higlass repo as it should be supported through the basic view header menu I believe.

**Comment by pkerpedjiev** [comment]
Do we want this to be part of the HiGlass client or app? I'm wary of adding new things to the component. It's already quite complex and has many dependencies so if this could be part of the app, I would personally much prefer that.

**Comment by nvictus** [comment]
Oh wow! @flekschas that looks really cool! ... but you're way ahead of me. I was referring to a viewconf **TEXT** editor UI to manually edit the viewconf in the browser. :)

**Comment by flekschas** [comment]
I agree, I think the app is a good place for it. The viewer should stay just that, the viewer to view data.

**Comment by flekschas** [comment]
Oh I see @nvictus. I think a in-browser viewConf JSON editor could be a first simple step.

**Comment by ngehlenborg** [comment]
What is meant to be configurable through the editor? Everything? And shouldn’t that be the same as HiGlass itself?

I think a basic editor that can used to visualize and describe the relationships between the views would be very helpful. It might be possible to represent that as one or more hierarchically organized lists.

On Nov 21, 2018, at 5:39 PM, Nezar Abdennur <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh wow! @flekschas<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_flekschas&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=QZVUUGi88RzVWuRwQIheWHxGpa4J1uEiazqb3igUFlI&s=p7kMLeFzutPQi-vMNONOw9IKW2hnlOaJGSKWI04Pw2Y&e=> that looks really cool! ... but you're way ahead of me. I was referring to a viewconf TEXT editor UI to manually edit the viewconf in the browser. :)

**Comment by flekschas** [comment]
Closing this as it's implemented since `v1.6` :)
